version: "3.3"

services:
## Alert: this image may cause a lot of pressure to system
#  elasticsearch:
#    container_name: elasticsearch
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
#    ports:
#    - 9200:9200
#    - 9300:9300
#    environment:
#      - xpack.security.enabled=false
#      - discovery.type=single-node
#    volumes:
#    - ~/IdeaProjects/Shediz/post/src/main/db/data:/usr/share/elasticsearch/data
  neo4j:
    container_name: neo4jdb
    image: neo4j:4.1.2
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_connector_https_advertised__address=localhost:7473
      - NEO4J_dbms_connector_http_advertised__address=localhost:7474
      - NEO4J_dbms_connector_bolt_advertised__address=localhost:7687
      - NEO4J_AUTH=neo4j/secret
    volumes:
      - ~/.Neo4jDesktop/neo4jDatabases/database-2750a9eb-15ab-49d2-bbc4-e9cf1c845eb3/installation-4.0.1/plugins:/plugins
      - ~/.Neo4jDesktop/neo4jDatabases/database-2750a9eb-15ab-49d2-bbc4-e9cf1c845eb3/installation-4.0.1/data:/data
      - ~/.Neo4jDesktop/neo4jDatabases/database-2750a9eb-15ab-49d2-bbc4-e9cf1c845eb3/installation-4.0.1/import:/import
      - ~/.Neo4jDesktop/neo4jDatabases/database-2750a9eb-15ab-49d2-bbc4-e9cf1c845eb3/installation-4.0.1/logs:/logs
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.9
    command: rabbitmq-server
    hostname: rabbitmq-service
    expose:
      - 5672
    ports:
    - 5672:5672
  discovery-service:
    container_name: discovery
    image: discovery-service:latest
    hostname: discovery-service
    ports:
    - 8761:8761
    environment:
      EUREKA_INSTANCE_HOSTNAME: discovery-service
  user-service:
    container_name: user
    image: user-service:latest
    hostname: user-service
    ports:
    - 8080:8080
    volumes:
    - ~/IdeaProjects/Shediz/gateway/src/main/db:/db
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
      EUREKA_INSTANCE_HOSTNAME: user-service
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - discovery-service
      - rabbitmq
  post-service:
    container_name: post
    image: post-service:latest
    hostname: post-service
    ports:
    - 8081:8081
    volumes:
    - ~/IdeaProjects/Shediz/post/src/main/db:/db
    environment:
      ELASTICSEARCH-HOST: host.docker.internal
      AUTH-HOST: user
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
      EUREKA_INSTANCE_HOSTNAME: post-service
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - discovery-service
      - rabbitmq
#      - elasticsearch
  recommender-service:
    container_name: recommender
    image: recommender-service:latest
    hostname: recommender-service
    ports:
    - 8082:8082
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
      EUREKA_INSTANCE_HOSTNAME: recommender-service
      SPRING_RABBITMQ_HOST: rabbitmq
      ORG_NEO4J_DRIVER_URI: bolt://neo4jdb
    depends_on:
      - discovery-service
      - rabbitmq
      - neo4j
  score-service:
    container_name: score
    image: score-service:latest
    hostname: score-service
    ports:
    - 8083:8083
    volumes:
    - ~/IdeaProjects/Shediz/score/src/main/db:/db
    environment:
      AUTH-HOST: user
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
      EUREKA_INSTANCE_HOSTNAME: score-service
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - discovery-service
      - rabbitmq
