server:
  port: 8083

spring:
  application:
    name: score-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:@project.basedir@/src/main/db/scores.db
    username:
    password:
  jpa:
    database-platform: com.shediz.score.dialect.SQLiteDialect
    show-sql: true
    properties:
      hibernate:
        format-sql: true

auth-host: localhost

gateway-secret: gateway-secret

rabbitmq:
  exchangeName: shediz.exchange
  queue1Name: usp-r.queue
  queue2Name: p-s.queue
  queue3Name: u-sp.queue # just for delete account
  routingKey: score.key

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
