server:
  port: 8081
spring:
  application:
    name: post-service
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

#ribbon:
#  eureka:
#    enabled: false

elasticsearch-host: localhost

auth-host: localhost

upload-dir: post/src/main/db

gateway-secret: gateway-secret

rabbitmq:
  exchangeName: shediz.exchange
  queue1Name: usp-r.queue
  queue2Name: p-s.queue
  queue3Name: u-sp.queue # just for delete account
  routingKey: post.key

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka